describe("Mass storage USB cleanup", function()
    it("stops the USB network gadget before entering USB storage", function()
        local file = assert(io.open("frontend/ui/elements/mass_storage.lua", "r"))
        local source = file:read("*a")
        file:close()

        assert.truthy(source:find("function MassStorage:stopUsbNetworkForStorage", 1, true))
        assert.truthy(source:find("self:stopUsbNetworkForStorage()", 1, true))
        assert.truthy(source:find("rmmod g_ether", 1, true))
        assert.truthy(source:find("'[k]obo-usb-dhcpd'", 1, true))
        assert.truthy(source:find("local was_running = self:isUsbNetworkRunning()", 1, true))
        assert.truthy(source:find('self:_usbNetworkCommand("recover")', 1, true))
        assert.is_nil(source:find("if not self:isUsbNetworkRunning() then", 1, true))
    end)
end)
