#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d)"
BACKUP=""

cleanup() {
  rm -rf "${TMP}"
  if [[ -n "${BACKUP}" ]]; then
    rm -rf "${BACKUP}"
  fi
}
trap cleanup EXIT

assert_file() {
  if [[ ! -f "$1" ]]; then
    echo "Missing file: $1" >&2
    exit 1
  fi
}

assert_executable() {
  if [[ ! -x "$1" ]]; then
    echo "Expected executable: $1" >&2
    exit 1
  fi
}

assert_contains() {
  local path="$1"
  local needle="$2"
  if ! rg -q "${needle}" "${path}"; then
    echo "Expected ${path} to contain ${needle}" >&2
    exit 1
  fi
}

make_stub_lib() {
  local path="$1"
  local marker="$2"
  printf 'const char *kobo_overlay_test_marker = "%s";\n' "${marker}" \
    | cc -shared -fPIC -x c -o "${path}" -
}

MOUNT="${TMP}/KOBOeReader"
KOREADER="${MOUNT}/.adds/koreader"
mkdir -p "${KOREADER}/frontend/document"
mkdir -p "${KOREADER}/frontend/apps/filemanager"
mkdir -p "${KOREADER}/frontend/apps/reader/modules"
mkdir -p "${KOREADER}/frontend/device"
mkdir -p "${KOREADER}/frontend/device/kobo"
mkdir -p "${KOREADER}/frontend/ui/elements"
mkdir -p "${KOREADER}/frontend/ui/network"
mkdir -p "${KOREADER}/frontend/ui/widget"
mkdir -p "${KOREADER}/frontend/ui/widget/container"
mkdir -p "${KOREADER}/ffi"
mkdir -p "${KOREADER}/bin"
mkdir -p "${KOREADER}/libs"
mkdir -p "${KOREADER}/plugins/SSH.koplugin"
mkdir -p "${KOREADER}/plugins/libra2perf.koplugin"
mkdir -p "${KOREADER}/plugins/ttsreader.koplugin"
LIB_STUB="${TMP}/libblitbuffer.so"
INPUT_STUB="${TMP}/libkoreader-input.so"
WRAP_STUB="${TMP}/libwrap-mupdf.so"
XXHASH_STUB="${TMP}/libxxhash.so.0"
XTEXT_STUB="${TMP}/libkoreader-xtext.so"
CRE_STUB="${TMP}/libkoreader-cre.so"
TTSPLAYER_STUB="${TMP}/libttsreader-player.so"
PLAYER_BIN_STUB="${TMP}/ttsreader-play"
DHCPD_STUB="${TMP}/kobo-usb-dhcpd"

printf 'old-defaults\n' >"${KOREADER}/defaults.lua"
printf 'old-blitbuffer-lua\n' >"${KOREADER}/ffi/blitbuffer.lua"
printf 'old-mupdf\n' >"${KOREADER}/ffi/mupdf.lua"
printf 'old-xxhash\n' >"${KOREADER}/ffi/xxhash.lua"
printf 'old-xxhash-h\n' >"${KOREADER}/ffi/xxhash_h.lua"
printf 'old-cache\n' >"${KOREADER}/frontend/cache.lua"
printf 'old-dispatcher\n' >"${KOREADER}/frontend/dispatcher.lua"
printf 'old-pluginloader\n' >"${KOREADER}/frontend/pluginloader.lua"
printf 'old-input\n' >"${KOREADER}/frontend/device/input.lua"
printf 'old-gesturedetector\n' >"${KOREADER}/frontend/device/gesturedetector.lua"
printf 'old-kobo-device\n' >"${KOREADER}/frontend/device/kobo/device.lua"
printf 'old-uimanager\n' >"${KOREADER}/frontend/ui/uimanager.lua"
printf 'old-network-manager\n' >"${KOREADER}/frontend/ui/network/manager.lua"
printf 'old-wpa-supplicant\n' >"${KOREADER}/frontend/ui/network/wpa_supplicant.lua"
printf 'old-credocument\n' >"${KOREADER}/frontend/document/credocument.lua"
printf 'old-doccache\n' >"${KOREADER}/frontend/document/doccache.lua"
printf 'old-document\n' >"${KOREADER}/frontend/document/document.lua"
printf 'old-kopt\n' >"${KOREADER}/frontend/document/koptinterface.lua"
printf 'old-documentregistry\n' >"${KOREADER}/frontend/document/documentregistry.lua"
printf 'old-filemanager\n' >"${KOREADER}/frontend/apps/filemanager/filemanager.lua"
printf 'old-filemanagerbookinfo\n' >"${KOREADER}/frontend/apps/filemanager/filemanagerbookinfo.lua"
printf 'old-filemanagercollection\n' >"${KOREADER}/frontend/apps/filemanager/filemanagercollection.lua"
printf 'old-filemanagerfilesearcher\n' >"${KOREADER}/frontend/apps/filemanager/filemanagerfilesearcher.lua"
printf 'old-filemanagerhistory\n' >"${KOREADER}/frontend/apps/filemanager/filemanagerhistory.lua"
printf 'old-filemanagermenu\n' >"${KOREADER}/frontend/apps/filemanager/filemanagermenu.lua"
printf 'old-filemanagershortcuts\n' >"${KOREADER}/frontend/apps/filemanager/filemanagershortcuts.lua"
printf 'old-filemanagerutil\n' >"${KOREADER}/frontend/apps/filemanager/filemanagerutil.lua"
printf 'old-readerui\n' >"${KOREADER}/frontend/apps/reader/readerui.lua"
printf 'old-readerfooter\n' >"${KOREADER}/frontend/apps/reader/modules/readerfooter.lua"
printf 'old-highlight\n' >"${KOREADER}/frontend/apps/reader/modules/readerhighlight.lua"
printf 'old-koptlistener\n' >"${KOREADER}/frontend/apps/reader/modules/readerkoptlistener.lua"
printf 'old-readermenu\n' >"${KOREADER}/frontend/apps/reader/modules/readermenu.lua"
printf 'old-readerview\n' >"${KOREADER}/frontend/apps/reader/modules/readerview.lua"
printf 'old-readerzooming\n' >"${KOREADER}/frontend/apps/reader/modules/readerzooming.lua"
printf 'old-readerrolling\n' >"${KOREADER}/frontend/apps/reader/modules/readerrolling.lua"
printf 'old-menusorter\n' >"${KOREADER}/frontend/ui/menusorter.lua"
printf 'old-reader-menu-order\n' >"${KOREADER}/frontend/ui/elements/reader_menu_order.lua"
printf 'old-filemanager-menu-order\n' >"${KOREADER}/frontend/ui/elements/filemanager_menu_order.lua"
printf 'old-mass-storage\n' >"${KOREADER}/frontend/ui/elements/mass_storage.lua"
printf 'old-eventlistener\n' >"${KOREADER}/frontend/ui/widget/eventlistener.lua"
printf 'old-networksetting\n' >"${KOREADER}/frontend/ui/widget/networksetting.lua"
printf 'old-inputcontainer\n' >"${KOREADER}/frontend/ui/widget/container/inputcontainer.lua"
printf 'old-widgetcontainer\n' >"${KOREADER}/frontend/ui/widget/container/widgetcontainer.lua"
printf 'old-filechooser\n' >"${KOREADER}/frontend/ui/widget/filechooser.lua"
printf 'old-libblitbuffer\n' >"${KOREADER}/libs/libblitbuffer.so"
printf 'old-libinput\n' >"${KOREADER}/libs/libkoreader-input.so"
printf 'old-libwrap-mupdf\n' >"${KOREADER}/libs/libwrap-mupdf.so"
printf 'old-libxxhash\n' >"${KOREADER}/libs/libxxhash.so.0"
printf 'old-libxtext\n' >"${KOREADER}/libs/libkoreader-xtext.so"
printf 'old-libcre\n' >"${KOREADER}/libs/libkoreader-cre.so"
printf 'old-ttsplayer\n' >"${KOREADER}/libs/libttsreader-player.so"
printf 'old-ttsreader-play\n' >"${KOREADER}/bin/ttsreader-play"
printf 'old-usb-dhcpd\n' >"${KOREADER}/bin/kobo-usb-dhcpd"
printf 'old-launcher\n' >"${KOREADER}/koreader.sh"
printf 'old-enable-wifi\n' >"${KOREADER}/enable-wifi.sh"
printf 'old-disable-wifi\n' >"${KOREADER}/disable-wifi.sh"
printf 'old-obtain-ip\n' >"${KOREADER}/obtain-ip.sh"
printf 'old-release-ip\n' >"${KOREADER}/release-ip.sh"
printf 'old-restore-wifi\n' >"${KOREADER}/restore-wifi-async.sh"
printf 'old-usb-network\n' >"${KOREADER}/usb-network-ssh.sh"
printf 'old-hook\n' >"${KOREADER}/libra2-optimize.sh"
printf 'old-preflight\n' >"${KOREADER}/libra2-preflight.lua"
printf 'old-ssh-plugin\n' >"${KOREADER}/plugins/SSH.koplugin/main.lua"
printf 'old-ssh-meta\n' >"${KOREADER}/plugins/SSH.koplugin/_meta.lua"
printf 'old-plugin\n' >"${KOREADER}/plugins/libra2perf.koplugin/_meta.lua"
printf 'old-tts-plugin\n' >"${KOREADER}/plugins/ttsreader.koplugin/_meta.lua"
make_stub_lib "${LIB_STUB}" "new-libblitbuffer"
make_stub_lib "${INPUT_STUB}" "new-libinput"
make_stub_lib "${WRAP_STUB}" "new-libwrap-mupdf"
make_stub_lib "${XXHASH_STUB}" "new-libxxhash"
make_stub_lib "${XTEXT_STUB}" "new-libxtext"
make_stub_lib "${CRE_STUB}" "new-libcre"
make_stub_lib "${TTSPLAYER_STUB}" "new-ttsplayer"
make_stub_lib "${PLAYER_BIN_STUB}" "new-ttsreader-play"
make_stub_lib "${DHCPD_STUB}" "new-usb-dhcpd"

output="$(KOBO_ALLOW_INCOMPATIBLE_NATIVE=1 KOBO_LIBBLITBUFFER_SO="${LIB_STUB}" KOBO_LIBINPUT_SO="${INPUT_STUB}" KOBO_LIBWRAP_MUPDF_SO="${WRAP_STUB}" KOBO_LIBXXHASH_SO="${XXHASH_STUB}" KOBO_LIBXTEXT_SO="${XTEXT_STUB}" KOBO_LIBCRE_SO="${CRE_STUB}" KOBO_LIBTTSREADER_PLAYER_SO="${TTSPLAYER_STUB}" KOBO_TTSREADER_PLAYER_BIN="${PLAYER_BIN_STUB}" KOBO_USB_DHCPD_BIN="${DHCPD_STUB}" "${ROOT}/scripts/deploy-libra2-overlay.sh" "${MOUNT}")"
BACKUP="$(printf '%s\n' "${output}" | sed -n 's/^Backup: //p')"

assert_file "${KOREADER}/defaults.lua"
assert_file "${KOREADER}/ffi/blitbuffer.lua"
assert_file "${KOREADER}/ffi/mupdf.lua"
assert_file "${KOREADER}/ffi/xxhash.lua"
assert_file "${KOREADER}/ffi/xxhash_h.lua"
assert_file "${KOREADER}/frontend/cache.lua"
assert_file "${KOREADER}/frontend/dispatcher.lua"
assert_file "${KOREADER}/frontend/pluginloader.lua"
assert_file "${KOREADER}/frontend/ui/uimanager.lua"
assert_file "${KOREADER}/frontend/document/credocument.lua"
assert_file "${KOREADER}/frontend/document/doccache.lua"
assert_file "${KOREADER}/frontend/document/document.lua"
assert_file "${KOREADER}/frontend/document/koptinterface.lua"
assert_file "${KOREADER}/frontend/document/documentregistry.lua"
assert_file "${KOREADER}/frontend/apps/filemanager/filemanager.lua"
assert_file "${KOREADER}/frontend/apps/filemanager/filemanagerbookinfo.lua"
assert_file "${KOREADER}/frontend/apps/filemanager/filemanagercollection.lua"
assert_file "${KOREADER}/frontend/apps/filemanager/filemanagerfilesearcher.lua"
assert_file "${KOREADER}/frontend/apps/filemanager/filemanagerhistory.lua"
assert_file "${KOREADER}/frontend/apps/filemanager/filemanagermenu.lua"
assert_file "${KOREADER}/frontend/apps/filemanager/filemanagershortcuts.lua"
assert_file "${KOREADER}/frontend/apps/filemanager/filemanagerutil.lua"
assert_file "${KOREADER}/frontend/apps/reader/readerui.lua"
assert_file "${KOREADER}/frontend/apps/reader/modules/readerfooter.lua"
assert_file "${KOREADER}/frontend/apps/reader/modules/readerhighlight.lua"
assert_file "${KOREADER}/frontend/apps/reader/modules/readerkoptlistener.lua"
assert_file "${KOREADER}/frontend/apps/reader/modules/readermenu.lua"
assert_file "${KOREADER}/frontend/apps/reader/modules/readerview.lua"
assert_file "${KOREADER}/frontend/apps/reader/modules/readerzooming.lua"
assert_file "${KOREADER}/frontend/apps/reader/modules/readerrolling.lua"
assert_file "${KOREADER}/frontend/ui/menusorter.lua"
assert_file "${KOREADER}/frontend/device/input.lua"
assert_file "${KOREADER}/frontend/device/gesturedetector.lua"
assert_file "${KOREADER}/frontend/device/kobo/device.lua"
assert_file "${KOREADER}/frontend/ui/elements/reader_menu_order.lua"
assert_file "${KOREADER}/frontend/ui/elements/filemanager_menu_order.lua"
assert_file "${KOREADER}/frontend/ui/elements/mass_storage.lua"
assert_file "${KOREADER}/frontend/ui/network/manager.lua"
assert_file "${KOREADER}/frontend/ui/network/wpa_supplicant.lua"
assert_file "${KOREADER}/frontend/ui/widget/eventlistener.lua"
assert_file "${KOREADER}/frontend/ui/widget/networksetting.lua"
assert_file "${KOREADER}/frontend/ui/widget/container/inputcontainer.lua"
assert_file "${KOREADER}/frontend/ui/widget/container/widgetcontainer.lua"
assert_file "${KOREADER}/frontend/ui/widget/filechooser.lua"
assert_file "${KOREADER}/libs/libblitbuffer.so"
assert_file "${KOREADER}/libs/libkoreader-input.so"
assert_file "${KOREADER}/libs/libwrap-mupdf.so"
assert_file "${KOREADER}/libs/libxxhash.so.0"
assert_file "${KOREADER}/libs/libkoreader-xtext.so"
assert_file "${KOREADER}/libs/libkoreader-cre.so"
assert_file "${KOREADER}/libs/libttsreader-player.so"
assert_file "${KOREADER}/bin/ttsreader-play"
assert_file "${KOREADER}/bin/kobo-usb-dhcpd"
assert_file "${KOREADER}/koreader.sh"
assert_file "${KOREADER}/enable-wifi.sh"
assert_file "${KOREADER}/disable-wifi.sh"
assert_file "${KOREADER}/obtain-ip.sh"
assert_file "${KOREADER}/release-ip.sh"
assert_file "${KOREADER}/restore-wifi-async.sh"
assert_file "${KOREADER}/usb-network-ssh.sh"
assert_file "${KOREADER}/libra2-optimize.sh"
assert_file "${KOREADER}/libra2-preflight.lua"
assert_file "${KOREADER}/plugins/SSH.koplugin/main.lua"
assert_file "${KOREADER}/plugins/libra2perf.koplugin/_meta.lua"
assert_file "${KOREADER}/plugins/ttsreader.koplugin/main.lua"
assert_executable "${KOREADER}/koreader.sh"
assert_executable "${KOREADER}/enable-wifi.sh"
assert_executable "${KOREADER}/disable-wifi.sh"
assert_executable "${KOREADER}/obtain-ip.sh"
assert_executable "${KOREADER}/release-ip.sh"
assert_executable "${KOREADER}/restore-wifi-async.sh"
assert_executable "${KOREADER}/usb-network-ssh.sh"
assert_executable "${KOREADER}/libra2-optimize.sh"
assert_executable "${KOREADER}/bin/ttsreader-play"
assert_executable "${KOREADER}/bin/kobo-usb-dhcpd"
assert_contains "${KOREADER}/ffi/blitbuffer.lua" "contiguous scanlines"
assert_contains "${KOREADER}/ffi/mupdf.lua" "draw_to_blitbuffer"
assert_contains "${KOREADER}/ffi/xxhash.lua" "xxh3_64_hex"
assert_contains "${KOREADER}/ffi/xxhash_h.lua" "XXH3_64bits"
assert_contains "${KOREADER}/frontend/cache.lua" "xxh3_64_hex"
assert_contains "${KOREADER}/frontend/dispatcher.lua" "libra2_disable_lookup_modules"
assert_contains "${KOREADER}/frontend/pluginloader.lua" "libra2_lazy_disabled_plugin_meta"
assert_contains "${KOREADER}/frontend/device/input.lua" "_handleTouchFrame"
assert_contains "${KOREADER}/frontend/device/gesturedetector.lua" "feedOneEvent"
assert_contains "${KOREADER}/frontend/device/kobo/device.lua" "fast_reconnect_timeout"
assert_contains "${KOREADER}/frontend/device/kobo/device.lua" "HeadsetPlayPause"
assert_contains "${KOREADER}/frontend/device/kobo/device.lua" "INPUT_VOLUME_BUTTONS"
assert_contains "${KOREADER}/frontend/device/kobo/device.lua" "getKoboWifiInterface"
assert_contains "${KOREADER}/frontend/device/kobo/device.lua" "wpa_supplicant/\" .. net_if"
assert_contains "${KOREADER}/frontend/ui/uimanager.lua" "nb_tasks"
assert_contains "${KOREADER}/frontend/ui/network/manager.lua" "fastReconnectToSavedNetwork"
assert_contains "${KOREADER}/frontend/ui/network/wpa_supplicant.lua" "show_ui"
assert_contains "${KOREADER}/frontend/document/credocument.lua" "regularizeRegisteredFontsWeights"
assert_contains "${KOREADER}/frontend/document/doccache.lua" "xxh3_64_hex"
assert_contains "${KOREADER}/frontend/document/document.lua" "is_full_page_tile"
assert_contains "${KOREADER}/frontend/document/documentregistry.lua" "registerLazyImageViewer"
assert_contains "${KOREADER}/frontend/document/koptinterface.lua" "_appendConfigurableHash"
assert_contains "${KOREADER}/frontend/apps/filemanager/filemanager.lua" "libra2_fast_filemanager_filter"
assert_contains "${KOREADER}/frontend/apps/filemanager/filemanagerbookinfo.lua" "getTextViewer"
assert_contains "${KOREADER}/frontend/apps/filemanager/filemanagercollection.lua" "getReadCollection"
assert_contains "${KOREADER}/frontend/apps/filemanager/filemanagerfilesearcher.lua" "getFileManagerConverter"
assert_contains "${KOREADER}/frontend/apps/filemanager/filemanagerhistory.lua" "getReadCollection"
assert_contains "${KOREADER}/frontend/apps/filemanager/filemanagermenu.lua" "sub_item_table_func"
assert_contains "${KOREADER}/frontend/apps/filemanager/filemanagershortcuts.lua" "getButtonDialog"
assert_contains "${KOREADER}/frontend/apps/filemanager/filemanagerutil.lua" "getConfirmBox"
assert_contains "${KOREADER}/frontend/apps/reader/readerui.lua" "libra2_disable_lookup_modules"
assert_contains "${KOREADER}/frontend/apps/reader/readerui.lua" "getReaderModule"
assert_contains "${KOREADER}/frontend/apps/reader/readerui.lua" "ReaderSidePanelProxy"
assert_contains "${KOREADER}/frontend/apps/reader/modules/readerfooter.lua" "libra2_skip_unchanged_footer_update"
assert_contains "${KOREADER}/frontend/apps/reader/modules/readerhighlight.lua" "disable_highlight_lookup_actions"
assert_contains "${KOREADER}/frontend/apps/reader/modules/readerkoptlistener.lua" "isOCRFallbackEnabled"
assert_contains "${KOREADER}/frontend/apps/reader/modules/readermenu.lua" "sub_item_table_func"
assert_contains "${KOREADER}/frontend/apps/reader/modules/readerview.lua" "getBottomReserve"
assert_contains "${KOREADER}/frontend/apps/reader/modules/readerzooming.lua" "getBottomReserve"
assert_contains "${KOREADER}/frontend/apps/reader/modules/readerrolling.lua" "getDocumentViewport"
assert_contains "${KOREADER}/frontend/ui/menusorter.lua" "optional_empty_menu"
assert_contains "${KOREADER}/frontend/ui/elements/reader_menu_order.lua" "KOMenu:disabled"
assert_contains "${KOREADER}/frontend/ui/elements/filemanager_menu_order.lua" "KOMenu:disabled"
assert_contains "${KOREADER}/frontend/ui/elements/mass_storage.lua" "cleanupBlockingProcesses"
assert_contains "${KOREADER}/frontend/ui/elements/mass_storage.lua" "USB cable SSH"
assert_contains "${KOREADER}/frontend/ui/elements/mass_storage.lua" "startUsbNetwork"
assert_contains "${KOREADER}/frontend/ui/elements/mass_storage.lua" "recover"
assert_contains "${KOREADER}/frontend/ui/widget/eventlistener.lua" "local handler"
assert_contains "${KOREADER}/frontend/ui/widget/networksetting.lua" "rememberConnectedNetwork"
assert_contains "${KOREADER}/frontend/ui/widget/container/inputcontainer.lua" "ordered_touch_zones"
assert_contains "${KOREADER}/frontend/ui/widget/container/widgetcontainer.lua" "for i = 1, #self do"
assert_contains "${KOREADER}/frontend/ui/widget/filechooser.lua" "libra2_fast_filemanager_sort"
assert_contains "${KOREADER}/libs/libblitbuffer.so" "new-libblitbuffer"
assert_contains "${KOREADER}/libs/libkoreader-input.so" "new-libinput"
assert_contains "${KOREADER}/libs/libwrap-mupdf.so" "new-libwrap-mupdf"
assert_contains "${KOREADER}/libs/libxxhash.so.0" "new-libxxhash"
assert_contains "${KOREADER}/libs/libkoreader-xtext.so" "new-libxtext"
assert_contains "${KOREADER}/libs/libkoreader-cre.so" "new-libcre"
assert_contains "${KOREADER}/libs/libttsreader-player.so" "new-ttsplayer"
assert_contains "${KOREADER}/bin/ttsreader-play" "new-ttsreader-play"
assert_contains "${KOREADER}/bin/kobo-usb-dhcpd" "new-usb-dhcpd"
assert_contains "${KOREADER}/koreader.sh" 'INTERFACE="wlan0"'
assert_contains "${KOREADER}/enable-wifi.sh" 'INTERFACE="wlan0"'
assert_contains "${KOREADER}/enable-wifi.sh" "wpa_ctrl_ready"
assert_contains "${KOREADER}/disable-wifi.sh" 'INTERFACE="wlan0"'
assert_contains "${KOREADER}/obtain-ip.sh" 'INTERFACE="wlan0"'
assert_contains "${KOREADER}/release-ip.sh" 'INTERFACE="wlan0"'
assert_contains "${KOREADER}/restore-wifi-async.sh" 'INTERFACE="wlan0"'
assert_contains "${KOREADER}/enable-wifi.sh" "power_save off"
assert_contains "${KOREADER}/obtain-ip.sh" "KOBO_DHCP_TIMEOUT"
assert_contains "${KOREADER}/obtain-ip.sh" "Wi-Fi is not associated yet; skipping DHCP"
assert_contains "${KOREADER}/restore-wifi-async.sh" "WPA_IFACE=.*INTERFACE"
assert_contains "${KOREADER}/usb-network-ssh.sh" "g_ether"
assert_contains "${KOREADER}/usb-network-ssh.sh" "192.168.2.2"
assert_contains "${KOREADER}/usb-network-ssh.sh" "udhcpd"
assert_contains "${KOREADER}/usb-network-ssh.sh" "kobo-usb-dhcpd"
assert_contains "${KOREADER}/usb-network-ssh.sh" "pid_cmd_has"
assert_contains "${KOREADER}/usb-network-ssh.sh" "tcp_port_listening"
assert_contains "${KOREADER}/usb-network-ssh.sh" "ssh_listening=1"
assert_contains "${KOREADER}/usb-network-ssh.sh" "recover_usb_network"
assert_contains "${KOREADER}/plugins/SSH.koplugin/main.lua" "onPrepareUSBMS"
assert_contains "${KOREADER}/plugins/SSH.koplugin/main.lua" "_watchdogTick"
assert_contains "${KOREADER}/plugins/SSH.koplugin/main.lua" "onNetworkConnected"
assert_contains "${KOREADER}/libra2-preflight.lua" "Preflight.run"
assert_contains "${KOREADER}/plugins/libra2perf.koplugin/preflight.lua" "isLibra2Version"
assert_contains "${KOREADER}/plugins/libra2perf.koplugin/_meta.lua" "Libra 2"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/_meta.lua" "Audio reading"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/main.lua" "text:synthesize"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/main.lua" "TTS onbellegi"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/main.lua" "Eksikleri indir"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/main.lua" "Sayfalari goster"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/main.lua" "TTSHeadsetPlayPause"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/main.lua" "avrcpInputDevices"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/main.lua" "onEvdevInputInsert"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/ttsengine.lua" "pageCacheStatus"
assert_contains "${KOREADER}/plugins/ttsreader.koplugin/ttsengine.lua" "clearPageCache"

if [[ ! -d "${MOUNT}/Books" ]]; then
  echo "Deploy should create Books folder" >&2
  exit 1
fi

if find "${KOREADER}" -maxdepth 1 -name '.libra2-overlay-stage-*' | rg -q .; then
  echo "Deploy stage directory was not cleaned" >&2
  exit 1
fi

assert_contains "${BACKUP}/.adds/koreader/defaults.lua" "old-defaults"
assert_contains "${BACKUP}/.adds/koreader/ffi/blitbuffer.lua" "old-blitbuffer-lua"
assert_contains "${BACKUP}/.adds/koreader/ffi/mupdf.lua" "old-mupdf"
assert_contains "${BACKUP}/.adds/koreader/ffi/xxhash.lua" "old-xxhash"
assert_contains "${BACKUP}/.adds/koreader/ffi/xxhash_h.lua" "old-xxhash-h"
assert_contains "${BACKUP}/.adds/koreader/frontend/cache.lua" "old-cache"
assert_contains "${BACKUP}/.adds/koreader/frontend/dispatcher.lua" "old-dispatcher"
assert_contains "${BACKUP}/.adds/koreader/frontend/pluginloader.lua" "old-pluginloader"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/uimanager.lua" "old-uimanager"
assert_contains "${BACKUP}/.adds/koreader/frontend/document/credocument.lua" "old-credocument"
assert_contains "${BACKUP}/.adds/koreader/frontend/document/doccache.lua" "old-doccache"
assert_contains "${BACKUP}/.adds/koreader/frontend/document/document.lua" "old-document"
assert_contains "${BACKUP}/.adds/koreader/frontend/document/koptinterface.lua" "old-kopt"
assert_contains "${BACKUP}/.adds/koreader/frontend/document/documentregistry.lua" "old-documentregistry"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/filemanager/filemanager.lua" "old-filemanager"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/filemanager/filemanagerbookinfo.lua" "old-filemanagerbookinfo"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/filemanager/filemanagercollection.lua" "old-filemanagercollection"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/filemanager/filemanagerfilesearcher.lua" "old-filemanagerfilesearcher"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/filemanager/filemanagerhistory.lua" "old-filemanagerhistory"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/filemanager/filemanagermenu.lua" "old-filemanagermenu"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/filemanager/filemanagershortcuts.lua" "old-filemanagershortcuts"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/filemanager/filemanagerutil.lua" "old-filemanagerutil"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/reader/readerui.lua" "old-readerui"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/reader/modules/readerfooter.lua" "old-readerfooter"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/reader/modules/readerhighlight.lua" "old-highlight"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/reader/modules/readerkoptlistener.lua" "old-koptlistener"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/reader/modules/readermenu.lua" "old-readermenu"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/reader/modules/readerview.lua" "old-readerview"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/reader/modules/readerzooming.lua" "old-readerzooming"
assert_contains "${BACKUP}/.adds/koreader/frontend/apps/reader/modules/readerrolling.lua" "old-readerrolling"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/menusorter.lua" "old-menusorter"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/elements/reader_menu_order.lua" "old-reader-menu-order"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/elements/filemanager_menu_order.lua" "old-filemanager-menu-order"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/elements/mass_storage.lua" "old-mass-storage"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/widget/eventlistener.lua" "old-eventlistener"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/widget/container/inputcontainer.lua" "old-inputcontainer"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/widget/container/widgetcontainer.lua" "old-widgetcontainer"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/widget/filechooser.lua" "old-filechooser"
assert_contains "${BACKUP}/.adds/koreader/frontend/device/input.lua" "old-input"
assert_contains "${BACKUP}/.adds/koreader/frontend/device/gesturedetector.lua" "old-gesturedetector"
assert_contains "${BACKUP}/.adds/koreader/frontend/device/kobo/device.lua" "old-kobo-device"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/network/manager.lua" "old-network-manager"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/network/wpa_supplicant.lua" "old-wpa-supplicant"
assert_contains "${BACKUP}/.adds/koreader/frontend/ui/widget/networksetting.lua" "old-networksetting"
assert_contains "${BACKUP}/.adds/koreader/libs/libblitbuffer.so" "old-libblitbuffer"
assert_contains "${BACKUP}/.adds/koreader/libs/libkoreader-input.so" "old-libinput"
assert_contains "${BACKUP}/.adds/koreader/libs/libwrap-mupdf.so" "old-libwrap-mupdf"
assert_contains "${BACKUP}/.adds/koreader/libs/libxxhash.so.0" "old-libxxhash"
assert_contains "${BACKUP}/.adds/koreader/libs/libkoreader-xtext.so" "old-libxtext"
assert_contains "${BACKUP}/.adds/koreader/libs/libkoreader-cre.so" "old-libcre"
assert_contains "${BACKUP}/.adds/koreader/libs/libttsreader-player.so" "old-ttsplayer"
assert_contains "${BACKUP}/.adds/koreader/bin/ttsreader-play" "old-ttsreader-play"
assert_contains "${BACKUP}/.adds/koreader/bin/kobo-usb-dhcpd" "old-usb-dhcpd"
assert_contains "${BACKUP}/.adds/koreader/koreader.sh" "old-launcher"
assert_contains "${BACKUP}/.adds/koreader/enable-wifi.sh" "old-enable-wifi"
assert_contains "${BACKUP}/.adds/koreader/disable-wifi.sh" "old-disable-wifi"
assert_contains "${BACKUP}/.adds/koreader/obtain-ip.sh" "old-obtain-ip"
assert_contains "${BACKUP}/.adds/koreader/release-ip.sh" "old-release-ip"
assert_contains "${BACKUP}/.adds/koreader/restore-wifi-async.sh" "old-restore-wifi"
assert_contains "${BACKUP}/.adds/koreader/usb-network-ssh.sh" "old-usb-network"
assert_contains "${BACKUP}/.adds/koreader/libra2-optimize.sh" "old-hook"
assert_contains "${BACKUP}/.adds/koreader/libra2-preflight.lua" "old-preflight"
assert_contains "${BACKUP}/.adds/koreader/plugins/SSH.koplugin/main.lua" "old-ssh-plugin"
assert_contains "${BACKUP}/.adds/koreader/plugins/SSH.koplugin/_meta.lua" "old-ssh-meta"
assert_contains "${BACKUP}/.adds/koreader/plugins/libra2perf.koplugin/_meta.lua" "old-plugin"
assert_contains "${BACKUP}/.adds/koreader/plugins/ttsreader.koplugin/_meta.lua" "old-tts-plugin"

echo "overlay deploy fixture passed"
